[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = ["src", "examples"]
typeCheckingMode = ["basic"]
strict = ["src", "examples"]

[tool.isort]
profile = "black"
src_paths = ["src", "examples"]
