[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = ["src", "examples", "tests"]
typeCheckingMode = ["basic"]
strict = ["src", "examples", "tests"]

[tool.isort]
profile = "black"
src_paths = ["src", "examples", "tests"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
